# Generated by Django 5.1.4 on 2024-12-20 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('stock', models.IntegerField(default=0, help_text='Current stock of the medication')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dosage_form', models.CharField(blank=True, choices=[('Tablet', 'Tablet'), ('Capsule', 'Capsule'), ('Syrup', 'Syrup'), ('Injection', 'Injection'), ('Cream', 'Cream'), ('Ointment', 'Ointment'), ('Gel', 'Gel'), ('Drops', 'Drops'), ('Inhaler', 'Inhaler'), ('Suppository', 'Suppository'), ('Patch', 'Patch'), ('Solution', 'Solution'), ('Suspension', 'Suspension'), ('Spray', 'Spray'), ('Lotion', 'Lotion'), ('Lozenge', 'Lozenge'), ('Powder', 'Powder'), ('Granules', 'Granules'), ('Mouthwash', 'Mouthwash'), ('Shampoo', 'Shampoo'), ('Gargle', 'Gargle'), ('Enema', 'Enema'), ('Mouth Paint', 'Mouth Paint'), ('Ear Drops', 'Ear Drops'), ('Nasal Drops', 'Nasal Drops'), ('Eye Drops', 'Eye Drops'), ('Eye Ointment', 'Eye Ointment'), ('Eye Gel', 'Eye Gel'), ('Ear Spray', 'Ear Spray'), ('Ear Gel', 'Ear Gel'), ('Ear Ointment', 'Ear Ointment')], help_text='The form in which the medication is available', max_length=255, null=True)),
                ('manufacturer', models.CharField(blank=True, help_text='The company that manufactures the medication', max_length=255, null=True)),
                ('expiry_date', models.DateField(blank=True, help_text='The date after which the medication should not be used', null=True)),
                ('category', models.CharField(blank=True, choices=[('Antibiotics', 'Antibiotics'), ('Antipyretics', 'Antipyretics'), ('Analgesics', 'Analgesics'), ('Antimalarials', 'Antimalarials'), ('Antacids', 'Antacids'), ('Antihistamines', 'Antihistamines'), ('Antifungals', 'Antifungals'), ('Antivirals', 'Antivirals'), ('Antitussives', 'Antitussives'), ('Expectorants', 'Expectorants'), ('Laxatives', 'Laxatives'), ('Antidiarrheals', 'Antidiarrheals'), ('Antispasmodics', 'Antispasmodics'), ('Antiemetics', 'Antiemetics'), ('Antihypertensives', 'Antihypertensives'), ('Anticoagulants', 'Anticoagulants'), ('Anticonvulsants', 'Anticonvulsants'), ('Antidepressants', 'Antidepressants'), ('Antipsychotics', 'Antipsychotics'), ('Antidiabetics', 'Antidiabetics')], help_text='The category of the medication based on its use in treatment', max_length=255, null=True)),
                ('prescription_required', models.BooleanField(default=False, help_text='Whether a prescription is required to purchase this medication')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RefillRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=255)),
                ('requested_at', models.DateTimeField(auto_now_add=True, help_text='The date and time at which the refill was requested')),
                ('approved_at', models.DateTimeField(blank=True, help_text='The date and time at which the refill was approved', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes for the refill request', null=True)),
                ('rejected_reason', models.TextField(blank=True, help_text='Reason for rejecting the refill request', null=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='The user who approved the refill', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refill_approved_by', to=settings.AUTH_USER_MODEL)),
                ('medication', models.ForeignKey(help_text='The medication for which the refill is requested', on_delete=django.db.models.deletion.CASCADE, related_name='refill_requests', to='medication.medication')),
                ('requested_by', models.ForeignKey(help_text='The user who requested the refill', on_delete=django.db.models.deletion.CASCADE, related_name='refill_requested_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
